/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ThumbnailRouteImport } from './routes/thumbnail'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WTokenRouteImport } from './routes/w.$token'
import { Route as RequestOrgSlugRouteImport } from './routes/request.$orgSlug'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AppBusinessosRouteImport } from './routes/_app/businessos'
import { Route as AppBusinessosIndexRouteImport } from './routes/_app/businessos/index'
import { Route as RequestStatusTokenRouteImport } from './routes/request.status.$token'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as IntakeOrgSlugHackathonRouteImport } from './routes/intake.$orgSlug.hackathon'
import { Route as AppBusinessosSourcesRouteImport } from './routes/_app/businessos/sources'
import { Route as AppBusinessosProfileRouteImport } from './routes/_app/businessos/profile'
import { Route as AppBusinessosMarketRouteImport } from './routes/_app/businessos/market'
import { Route as AppBusinessosFinanceRouteImport } from './routes/_app/businessos/finance'
import { Route as AppBusinessosActionsRouteImport } from './routes/_app/businessos/actions'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicCronDailyDigestRouteImport } from './routes/api/public/cron/daily-digest'
import { Route as ApiPublicCronClusterRetrosRouteImport } from './routes/api/public/cron/cluster-retros'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ThumbnailRoute = ThumbnailRouteImport.update({
  id: '/thumbnail',
  path: '/thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WTokenRoute = WTokenRouteImport.update({
  id: '/w/$token',
  path: '/w/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestOrgSlugRoute = RequestOrgSlugRouteImport.update({
  id: '/request/$orgSlug',
  path: '/request/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBusinessosRoute = AppBusinessosRouteImport.update({
  id: '/businessos',
  path: '/businessos',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessosIndexRoute = AppBusinessosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBusinessosRoute,
} as any)
const RequestStatusTokenRoute = RequestStatusTokenRouteImport.update({
  id: '/request/status/$token',
  path: '/request/status/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeOrgSlugHackathonRoute = IntakeOrgSlugHackathonRouteImport.update({
  id: '/intake/$orgSlug/hackathon',
  path: '/intake/$orgSlug/hackathon',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBusinessosSourcesRoute = AppBusinessosSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppBusinessosRoute,
} as any)
const AppBusinessosProfileRoute = AppBusinessosProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppBusinessosRoute,
} as any)
const AppBusinessosMarketRoute = AppBusinessosMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppBusinessosRoute,
} as any)
const AppBusinessosFinanceRoute = AppBusinessosFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppBusinessosRoute,
} as any)
const AppBusinessosActionsRoute = AppBusinessosActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppBusinessosRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyDigestRoute =
  ApiPublicCronDailyDigestRouteImport.update({
    id: '/api/public/cron/daily-digest',
    path: '/api/public/cron/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronClusterRetrosRoute =
  ApiPublicCronClusterRetrosRouteImport.update({
    id: '/api/public/cron/cluster-retros',
    path: '/api/public/cron/cluster-retros',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thumbnail': typeof ThumbnailRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/businessos': typeof AppBusinessosRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/request/$orgSlug': typeof RequestOrgSlugRoute
  '/w/$token': typeof WTokenRoute
  '/businessos/actions': typeof AppBusinessosActionsRoute
  '/businessos/finance': typeof AppBusinessosFinanceRoute
  '/businessos/market': typeof AppBusinessosMarketRoute
  '/businessos/profile': typeof AppBusinessosProfileRoute
  '/businessos/sources': typeof AppBusinessosSourcesRoute
  '/intake/$orgSlug/hackathon': typeof IntakeOrgSlugHackathonRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/request/status/$token': typeof RequestStatusTokenRoute
  '/businessos/': typeof AppBusinessosIndexRoute
  '/api/public/cron/cluster-retros': typeof ApiPublicCronClusterRetrosRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thumbnail': typeof ThumbnailRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/request/$orgSlug': typeof RequestOrgSlugRoute
  '/w/$token': typeof WTokenRoute
  '/businessos/actions': typeof AppBusinessosActionsRoute
  '/businessos/finance': typeof AppBusinessosFinanceRoute
  '/businessos/market': typeof AppBusinessosMarketRoute
  '/businessos/profile': typeof AppBusinessosProfileRoute
  '/businessos/sources': typeof AppBusinessosSourcesRoute
  '/intake/$orgSlug/hackathon': typeof IntakeOrgSlugHackathonRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/request/status/$token': typeof RequestStatusTokenRoute
  '/businessos': typeof AppBusinessosIndexRoute
  '/api/public/cron/cluster-retros': typeof ApiPublicCronClusterRetrosRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thumbnail': typeof ThumbnailRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_app/businessos': typeof AppBusinessosRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/request/$orgSlug': typeof RequestOrgSlugRoute
  '/w/$token': typeof WTokenRoute
  '/_app/businessos/actions': typeof AppBusinessosActionsRoute
  '/_app/businessos/finance': typeof AppBusinessosFinanceRoute
  '/_app/businessos/market': typeof AppBusinessosMarketRoute
  '/_app/businessos/profile': typeof AppBusinessosProfileRoute
  '/_app/businessos/sources': typeof AppBusinessosSourcesRoute
  '/intake/$orgSlug/hackathon': typeof IntakeOrgSlugHackathonRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/request/status/$token': typeof RequestStatusTokenRoute
  '/_app/businessos/': typeof AppBusinessosIndexRoute
  '/api/public/cron/cluster-retros': typeof ApiPublicCronClusterRetrosRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/reset-password'
    | '/thumbnail'
    | '/unsubscribe'
    | '/businessos'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/r/$slug'
    | '/request/$orgSlug'
    | '/w/$token'
    | '/businessos/actions'
    | '/businessos/finance'
    | '/businessos/market'
    | '/businessos/profile'
    | '/businessos/sources'
    | '/intake/$orgSlug/hackathon'
    | '/lovable/email/suppression'
    | '/request/status/$token'
    | '/businessos/'
    | '/api/public/cron/cluster-retros'
    | '/api/public/cron/daily-digest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/reset-password'
    | '/thumbnail'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/r/$slug'
    | '/request/$orgSlug'
    | '/w/$token'
    | '/businessos/actions'
    | '/businessos/finance'
    | '/businessos/market'
    | '/businessos/profile'
    | '/businessos/sources'
    | '/intake/$orgSlug/hackathon'
    | '/lovable/email/suppression'
    | '/request/status/$token'
    | '/businessos'
    | '/api/public/cron/cluster-retros'
    | '/api/public/cron/daily-digest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/thumbnail'
    | '/unsubscribe'
    | '/_app/businessos'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/r/$slug'
    | '/request/$orgSlug'
    | '/w/$token'
    | '/_app/businessos/actions'
    | '/_app/businessos/finance'
    | '/_app/businessos/market'
    | '/_app/businessos/profile'
    | '/_app/businessos/sources'
    | '/intake/$orgSlug/hackathon'
    | '/lovable/email/suppression'
    | '/request/status/$token'
    | '/_app/businessos/'
    | '/api/public/cron/cluster-retros'
    | '/api/public/cron/daily-digest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ThumbnailRoute: typeof ThumbnailRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RSlugRoute: typeof RSlugRoute
  RequestOrgSlugRoute: typeof RequestOrgSlugRoute
  WTokenRoute: typeof WTokenRoute
  IntakeOrgSlugHackathonRoute: typeof IntakeOrgSlugHackathonRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  RequestStatusTokenRoute: typeof RequestStatusTokenRoute
  ApiPublicCronClusterRetrosRoute: typeof ApiPublicCronClusterRetrosRoute
  ApiPublicCronDailyDigestRoute: typeof ApiPublicCronDailyDigestRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thumbnail': {
      id: '/thumbnail'
      path: '/thumbnail'
      fullPath: '/thumbnail'
      preLoaderRoute: typeof ThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$token': {
      id: '/w/$token'
      path: '/w/$token'
      fullPath: '/w/$token'
      preLoaderRoute: typeof WTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$orgSlug': {
      id: '/request/$orgSlug'
      path: '/request/$orgSlug'
      fullPath: '/request/$orgSlug'
      preLoaderRoute: typeof RequestOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/businessos': {
      id: '/_app/businessos'
      path: '/businessos'
      fullPath: '/businessos'
      preLoaderRoute: typeof AppBusinessosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/businessos/': {
      id: '/_app/businessos/'
      path: '/'
      fullPath: '/businessos/'
      preLoaderRoute: typeof AppBusinessosIndexRouteImport
      parentRoute: typeof AppBusinessosRoute
    }
    '/request/status/$token': {
      id: '/request/status/$token'
      path: '/request/status/$token'
      fullPath: '/request/status/$token'
      preLoaderRoute: typeof RequestStatusTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$orgSlug/hackathon': {
      id: '/intake/$orgSlug/hackathon'
      path: '/intake/$orgSlug/hackathon'
      fullPath: '/intake/$orgSlug/hackathon'
      preLoaderRoute: typeof IntakeOrgSlugHackathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/businessos/sources': {
      id: '/_app/businessos/sources'
      path: '/sources'
      fullPath: '/businessos/sources'
      preLoaderRoute: typeof AppBusinessosSourcesRouteImport
      parentRoute: typeof AppBusinessosRoute
    }
    '/_app/businessos/profile': {
      id: '/_app/businessos/profile'
      path: '/profile'
      fullPath: '/businessos/profile'
      preLoaderRoute: typeof AppBusinessosProfileRouteImport
      parentRoute: typeof AppBusinessosRoute
    }
    '/_app/businessos/market': {
      id: '/_app/businessos/market'
      path: '/market'
      fullPath: '/businessos/market'
      preLoaderRoute: typeof AppBusinessosMarketRouteImport
      parentRoute: typeof AppBusinessosRoute
    }
    '/_app/businessos/finance': {
      id: '/_app/businessos/finance'
      path: '/finance'
      fullPath: '/businessos/finance'
      preLoaderRoute: typeof AppBusinessosFinanceRouteImport
      parentRoute: typeof AppBusinessosRoute
    }
    '/_app/businessos/actions': {
      id: '/_app/businessos/actions'
      path: '/actions'
      fullPath: '/businessos/actions'
      preLoaderRoute: typeof AppBusinessosActionsRouteImport
      parentRoute: typeof AppBusinessosRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-digest': {
      id: '/api/public/cron/daily-digest'
      path: '/api/public/cron/daily-digest'
      fullPath: '/api/public/cron/daily-digest'
      preLoaderRoute: typeof ApiPublicCronDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cluster-retros': {
      id: '/api/public/cron/cluster-retros'
      path: '/api/public/cron/cluster-retros'
      fullPath: '/api/public/cron/cluster-retros'
      preLoaderRoute: typeof ApiPublicCronClusterRetrosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppBusinessosRouteChildren {
  AppBusinessosActionsRoute: typeof AppBusinessosActionsRoute
  AppBusinessosFinanceRoute: typeof AppBusinessosFinanceRoute
  AppBusinessosMarketRoute: typeof AppBusinessosMarketRoute
  AppBusinessosProfileRoute: typeof AppBusinessosProfileRoute
  AppBusinessosSourcesRoute: typeof AppBusinessosSourcesRoute
  AppBusinessosIndexRoute: typeof AppBusinessosIndexRoute
}

const AppBusinessosRouteChildren: AppBusinessosRouteChildren = {
  AppBusinessosActionsRoute: AppBusinessosActionsRoute,
  AppBusinessosFinanceRoute: AppBusinessosFinanceRoute,
  AppBusinessosMarketRoute: AppBusinessosMarketRoute,
  AppBusinessosProfileRoute: AppBusinessosProfileRoute,
  AppBusinessosSourcesRoute: AppBusinessosSourcesRoute,
  AppBusinessosIndexRoute: AppBusinessosIndexRoute,
}

const AppBusinessosRouteWithChildren = AppBusinessosRoute._addFileChildren(
  AppBusinessosRouteChildren,
)

interface AppRouteChildren {
  AppBusinessosRoute: typeof AppBusinessosRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppBusinessosRoute: AppBusinessosRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ThumbnailRoute: ThumbnailRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InviteTokenRoute: InviteTokenRoute,
  RSlugRoute: RSlugRoute,
  RequestOrgSlugRoute: RequestOrgSlugRoute,
  WTokenRoute: WTokenRoute,
  IntakeOrgSlugHackathonRoute: IntakeOrgSlugHackathonRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  RequestStatusTokenRoute: RequestStatusTokenRoute,
  ApiPublicCronClusterRetrosRoute: ApiPublicCronClusterRetrosRoute,
  ApiPublicCronDailyDigestRoute: ApiPublicCronDailyDigestRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
